### ISSUE TITLE
학습모델 다운로드 링크

### ISSUE THREAD

**Issue by nirvnana13** [gyunggyung/Korean-GPT2#1]
안녕하세요~
열심히 제작하신 코드 너무 감사합니다~
다름이 아니라 구글 드라이브에 업로드하신 학습모델도 같이 다운받아 보고 싶은데
기한이 지났는지 404에러가 났네요ㅠㅠ
혹시 링크 다시 부활시켜주실수는 없으실지 여쭤봅니다^^;

**Comment by gyunggyung** [comment]
안녕하세요 :) 지웠다면 아마 공개는 안 할 거 같습니다. 그리고

이 Repository는 더 이상 관리하지 않고 있습니다. https://github.com/gyunggyung/KoGPT2-FineTuning 이곳을 이용해주세요 :)
